name: CI

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Download ngrok
        run: Invoke-WebRequest -Uri https://bin.equinox.io/c/bwy%20j1mowac/ngrok-v?-stable-windows-amd64.zip -OutFile ngrok.zip

      - name: Extract ngrok
        run: Expand-Archive ngrok.zip -DestinationPath .\.ngrok

      - name: Authenticate with ngrok (Secure Way)
        # Use a secret for ngrok auth token
        run: .\.ngrok\ngrok.exe authtoken ${{ secrets.NGROK_AUTH_TOKEN }}

      - env:
          # Optional environment variables for ngrok configuration (if needed)
          NGROK_REGION: ${{ secrets.NGROK_REGION }}  # Example: us
          # ... other ngrok environment variables

      - name: Use ngrok (Example: Create an SSH tunnel)
        # Replace with your specific ngrok command (e.g., ngrok http 8080)
        run: .\.ngrok\ngrok.exe ssh -c "command to run"

    env:
      # Securely store ngrok auth token as a GitHub Secret
      nGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
