name: CI

on: [push, workflow_dispatch]

 jobs:
   build:

   runs-on: windows- latest

  steps:
 - name: Download
  run: invoke-WebRequest https://bin.equinox.io/c/BNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip -OutFile ngrok.zip
 - name: Extrect
  run: Expand-Archive ngrok.zip
 - name: Auth
  run: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
  env:
  NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
 - name: Enable TS
  run: Set_ItemProperty -path 'HKLM:\System\CurrentControlSet\Control\Terminal Servr' -name "fDenyTSConnections" -Value 0
 - run: Enable-NetFirewallRule -DisplayGroup "Remote DesKtop"
 - run: Set-ItemProperty _peth 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
 - run: Set-LocalUser -NME "runneradmin" -Password (ConvertTo-SecureString _AsPlainText "p@ssw0rd!" -Force)
 - name: Create Tunnel
  run: .\ngrok\ngrok.exe tcp 3389
